### ISSUE TITLE
Option to store snippets outside of workspace?

### ISSUE THREAD

**Issue by gunn4r** [snipsnapdev/snipsnap-vscode#10]
Great extension. Seriously awesome.  

In the monorepo I work with at work we have our .vscode workspace folder checked into git, and they dont want snipsnap's snippets pushed into the repo. Is there anyway to utilize this where the snippets are not stored in the workspaces .vscode directory?

**Comment by lnikell** [comment]
Hi @gunn4r, Thank you for the feedback. Do you think adding .vscode/snipsnap.code-snippets to .gitignore will work for you?
Maybe I did not get right, so please feel free to elaborate more on this. In our team, we have Snipsnap added in .gitignore in most of the projects, since every dev uses it anyway.

**Comment by gunn4r** [comment]
Hah yeah I can just go that route. Was hoping to avoid a root dir approval (we have a very large monorepo) is all if there was an easy way to shift the snippets out of workspace .vscode folder.

No worries. Thanks again for the dope extension!
